server/models/account.py
from server import db
from flask_login import UserMixin
from sqlalchemy.sql import func

class User(db.Model, UserMixin):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50))
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(50))
    joined = db.Column(db.DateTime(timezone=True), default=func.now())
    posts = db.relationship('Posts', backref="user", passive_deletes=True)

server/models/posts.py
from server import db
from sqlalchemy.sql import func

class Posts(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    author = db.Column(db.Integer, db.ForeignKey('user.id', ondelete="CASCADE"), nullable=False)
    text = db.Column(db.Text, nullable=False)
    created_at = db.Column(db.DateTime(timezone=True), default=func.now())

server/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from decouple import config

db = SQLAlchemy()
DB_NAME = config('DB_NAME')

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = config('SECRET_KEY')
    app.config['SQLALCHEMY_DATABASE_URI'] = f"sqlite:///{DB_NAME}"
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/auth/")

    from .models.account import User
    from .models.posts import Posts

    with app.app_context():
        create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = "auth.login"
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app

def create_database(app):
    if not os.path.exists("server/" + DB_NAME):
        db.create_all()
        print("Database created")

server/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from .models.account import User

auth = Blueprint("auth", __name__)

@auth.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("views.home"))
    else:
        if request.method == "POST":
            email = request.form.get('email')
            password = request.form.get('password')
            user = User.query.filter_by(email=email).first()
            if user:
                if check_password_hash(user.password, password):
                    login_user(user, remember=True)
                    flash(message='Logged In', category="success")
                    return redirect(url_for("views.home"))
                else:
                    flash(message='Incorrect Password.', category="error")
            else:
                flash(message='User does not exist.', category="error")
        return render_template("pages/login.html", user=current_user)

@auth.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        username = request.form.get('username')
        email = request.form.get('email')
        password = request.form.get('password')
        password2 = request.form.get('password2')
        print(username, email, password, password2)
        isExists = User.query.filter_by(email=email).first()
        if isExists:
            flash(message='Email is already registered.', category="error")
        elif password != password2:
            flash(message='Password doesn\'t match.', category="error")
        else:
            new_user = User(username=username, email=email, password=generate_password_hash(password))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash(message='Registerd Successfully.', category="success")
            return redirect(url_for("views.home"))
    return render_template("pages/register.html", user=current_user)

@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("views.home"))

server/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import current_user
from . import db
from .models.posts import Posts

views = Blueprint("views", __name__)

@views.route("/")
@views.route("/home")
def home():
    posts = Posts.query.all()
    context = {
        "user": current_user,
        "posts": posts
    }
    return render_template("pages/index.html", **context)

@views.route("/create-post", methods=["GET", "POST"])
def create_post():
    if current_user.is_authenticated:
        if request.method == "POST":
            text = request.form.get("text")
            if not text:
                flash(message="Post cannot be empty", category="error")
            else:
                post = Posts(text=text, author=current_user.id)
                db.session.add(post)
                db.session.commit()
                flash(message="Post Created!", category="success")
                return redirect(url_for("views.home"))
        return render_template("pages/create_post.html", user=current_user)
    else:
        return redirect(url_for("views.home"))
    

@views.route("/delete-post/<int:id>")
def delete_post(id):
    post = Posts.query.get_or_404(id)
    if post.author == current_user.id:
        db.session.delete(post)
        db.session.commit()
        flash("Post deleted successfully", "success")
    else:
        flash("You are not authorized to delete this post", "danger")
    return redirect(url_for("views.home"))

server/templates/includes/messages.html
<div class="w-100">
  {% with messages = get_flashed_messages(with_categories=True) %}
  <!--  -->
  {% if messages %}
  <!--  -->
  {% for category, message in messages %}
  <!--  -->
  {% if category == "error" %}
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
  </div>
  {% else %}
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
  </div>
  {% endif %}
  <!--  -->
  {% endfor %}
  <!--  -->
  {% endif %}
  <!--  -->
  {% endwith %}
</div>

server/templates/includes/navbar.html
<nav
  class="navbar navbar-expand-lg bg-dark p-3 position-fixed w-100 z-3"
  data-bs-theme="dark"
>
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            href="{{url_for('views.home')}}"
            >Home</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.login')}}">Posts</a>
        </li>
        {% if not user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.register')}}">Register</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.login')}}">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.logout')}}">Logout</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

server/templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BlogPoint | {% block title %}{% endblock %}</title>
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/styles.css')}}"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
  </head>
  <body>
    {% include "includes/navbar.html" %}
    <!--  -->
    <div class="content">
      {% include "includes/messages.html" %} {% block content %}{% endblock %}
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

server/templates/pages/create_post.html
{% extends "layout/base.html" %}
<!--  -->
{% block title %} create post {% endblock %}
<!--  -->

{% block content %}
<form method="post">
  <h1 class="mb-3">Create post</h1>
  <textarea name="text" rows="5" class="w-100 form-control"></textarea>
  <button class="btn btn-sm btn-success float-end my-3" type="submit">
    Submit
  </button>
</form>
{% endblock %}

server/templates/pages/index.html
{% extends "layout/base.html" %}
<!--  -->
{% block title %}home{% endblock %}
<!--  -->
{% block content %}
<div class="">
  <h1 class="">Posts</h1>
  {% for post in posts %}
  <div class="card my-3">
    <div class="card-header">
      <a class="text-capitalize text-dark text-decoration-none fw-bolder"
        >{{post.user.username}}</a
      >
      {% if post.user == user %}
      <div class="btn-group float-end">
        <button
          type="button"
          class="btn btn-sm dropdown-toggle"
          data-bs-toggle="dropdown"
        ></button>
        <ul class="dropdown-menu">
          <li>
            <a
              href="{{url_for('views.delete_post', id=post.id)}}"
              class="dropdown-item"
              >Delete</a
            >
          </li>
        </ul>
      </div>
      {% endif %}
    </div>
    <div class="card-body">
      <p class="card-text">{{post.text}}</p>
    </div>
    <div class="card-footer text-muted">{{post.created_at}}</div>
  </div>
  {% endfor %}
</div>
{% endblock %}
<!--  -->

server/templates/pages/login.html
{% extends "layout/base.html" %}
<!--  -->
{% block title %}Login{% endblock %}
<!--  -->
{% block content %}
<div
  class="d-flex justify-content-center align-items-center"
  style="height: 80vh"
>
  <form action="" method="post">
    <h1 class="text-center">Login</h1>
    <div class="position-relative">
      <label class="d-block">Email</label>
      <input type="email" name="email" class="form-control" required />
    </div>
    <div class="position-relative">
      <label class="d-block">Password</label>
      <input type="password" name="password" class="form-control" required />
    </div>
    <button class="btn btn-sm btn-success float-end my-3" type="submit">
      submit
    </button>
  </form>
</div>
{% endblock %}
<!--  -->

server/templates/pages/register.html
{% extends "layout/base.html" %}
<!--  -->
{% block title %}Register{% endblock %}
<!--  -->
{% block content %}
<div
  class="d-flex justify-content-center align-items-center"
  style="height: 80vh"
>
  <form method="post">
    <h1 class="text-center">Register</h1>
    <div class="position-relative">
      <label class="d-block">Username</label>
      <input type="text" name="username" class="form-control" required />
    </div>
    <div class="position-relative">
      <label class="d-block">Email</label>
      <input type="email" name="email" class="form-control" required />
    </div>
    <div class="position-relative">
      <label class="d-block">Password</label>
      <input type="password" name="password" class="form-control" required />
    </div>
    <div class="position-relative">
      <label class="d-block">Confirm Password</label>
      <input type="password" name="password2" class="form-control" required />
    </div>
    <button class="btn btn-sm btn-success float-end my-3" type="submit">
      submit
    </button>
  </form>
</div>

{% endblock %}
<!--  -->